// Kevin McEnroe D00242092
package com.dkit.gd2.kevinmcenroe;

public enum ComputerBookingMainMenu {
    QUIT_BOOKING_MENU,
    ADD_BOOKING,
    EDIT_BOOKING,
    DELETE_BOOKING,
    PRINT_BOOKING,
    PRINT_ALL_BOOKINGS,
    PRINT_BOOKINGS_FOR_STUDENT,
    PRINT_AVERAGE_BOOKING_LENGTH,
    PRINT_BOOKING_STATISTICS,
    RETURN_BOOKED_COMPUTER;
}
